[versions]
room = "2.3.0"
work = "2.7.0"
appcompat = "1.6.1"
core_ktx = "1.6.0"
constraint_layout = "2.1.1"
swipe_refresh_layout = "1.1.0"
navigation = "2.6.0"
lifecycle = "2.4.0"
material = "1.9.0"
retrofit = "2.9.0"
dagger = "2.45"
yandex_auth = "2.5.1"
logging_interceptor_okhttp = "4.9.1"
junit = "4.13.2"
android_junit = "1.1.3"
espresso_core = "3.4.0"
compose = "1.4.3"
compose_material3 = "1.1.1"
coordinatorlayout = "1.2.0"
kotlin = "1.8.20"
agp = "8.0.2"

[libraries]
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger_compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
work = { group = "androidx.work", name = "work-runtime", version.ref = "work" }
work_ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room_compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room_ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room_runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
yandex_auth = { group = "com.yandex.android", name = "authsdk", version.ref = "yandex_auth" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit_converter_gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
logging_interceptor_okhttp = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging_interceptor_okhttp" }
core_ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core_ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraint_layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint_layout" }
swipe_refresh_layout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipe_refresh_layout" }
lifecycle_viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle_runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
navigation_fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation_ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
android_junit = { group = "androidx.test.ext", name = "junit", version.ref = "android_junit" }
espresso_core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso_core" }
compose_ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose_ui_tooling_preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose_ui_tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose_foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose_material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose_material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose_material3" }
coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
kotlin_gradle_plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
data_binding = { group = "androidx.databinding", name = "viewbinding", version.ref = "agp" }

[plugins]
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android_library = { id = "com.android.library", version.ref = "agp" }
android_application = { id = "com.android.application", version.ref = "agp" }
navigation_safe_args = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
kotlin_kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
